services:
  - type: web
    name: triplea-feedback-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn bot:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: SHEET_ID
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_BASE64
        sync: false
      - key: ADMINS
        sync: false
      - key: LOCALE
        value: ru

